### ISSUE TITLE
Памылка `Spatie\Permission\Traits\HasRoles` not found (on Scrutinizer CI build)

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#210]
https://scrutinizer-ci.com/g/diglabby/doika/inspections/4ff1a7ca-002d-4567-8a68-a3a8ae3174e3

```
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

FPHP Fatal error:  Trait 'Spatie\Permission\Traits\HasRoles' not found in /home/scrutinizer/build/app/Models/Auth/User.php on line 21
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php:945
Stack trace:
#0 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): in /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 945

Fatal error: Trait 'Spatie\Permission\Traits\HasRoles' not found in /home/scrutinizer/build/app/Models/Auth/User.php on line 21

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php:945
Stack trace:
#0 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): in /home/scrutinizer/build/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 945
```

**Comment by lptn** [comment]
@fr0zen 
`User` model выкарыстоўвае  `Spatie\Permission\Traits\HasRoles` trait, але відаць пакет Spatie\Permission выпелены з праекта

Калі ласкай дай нейкую гісторыю гэтага пакета на нашым праекце, каб адрэашаваць на гэты баг найбольш адэкватна

**Comment by fr0zen** [comment]
@lptn было вырашана, што прыбіраем функцыянал, які не выкарыстоўваецца, таму рабілася чыстка. Тут залежнасці засталіся, я іх выдалю

**Comment by lptn** [comment]
@fr0zen 
>Тут залежнасці засталіся, я іх выдалю

чаем. гэта тое, што стапаріць нас зараз (трэба мець зяленыя білды каб можна рухацца далей з CI  і CD)

**Comment by rizomaa** [comment]
@lptn @fr0zen ці гэта дублюючая задача? 
https://github.com/diglabby/doika/issues/226

**Comment by fr0zen** [comment]
@rizomaa не зусім, лепш калі будуць асобна.

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/pull/228

**Comment by Tyuba4** [comment]
Праблема вырашыцца з закрыццем issue #258
